name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      - run: echo -n ${{ secrets.KEYSTORE }} | base64 -d > android/release.keystore
      - run: flutter build appbundle --release --obfuscate --split-debug-info=build/debug-info --build-number=${{ github.run_number }}
        env:
          ORG_GRADLE_PROJECT_storePassword: ${{ secrets.STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_keyAlias: ${{ secrets.KEY_ALIAS }}
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: aab
          path: build/app/outputs/bundle/release/app-release.aab
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: debug-info
          path: build/debug-info
